### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by anggapurnajiwa** [crypto-bender/vote-system#1]
Hi, I love your repo. It's simple and straightforward. I'm using your repo in my presentation about blockchain to my colleagues.

I just see unused parameters here
https://github.com/haechi00/vote-system/blob/015bd5cb4ac60b9f3a2bec1635249563a3f56413/frontend/src/components/Dapp.js#L52

And also I would like to recommend you to use monorepo. So the solidity folder (hardhat), and frontend can be on the same directory instead of the frontend inside the hardhat. Just a matter of good structure.

But overall I love your work! Appreciate it!

**Comment by haechi00** [comment]
Yep! You are right. I was still learning back then when I did the tutorial. But yes, the structure is messy hahaha.

There are so many things that can be improve. I might try to a do a more advanced clean one someday. But I don't have enough time :(

It is not even on testnet nor production. That would be a good tutorial to push it to prod. Verify contracts, etc...But this tutorials takes so much time.

Anyways thanks for the kind words, I appreciate them. Feel free to fork it and improve it. :)
